//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Website.Resources.EmailTemplate", typeof(EmailTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào bạn {0}, &lt;br&gt;&lt;br&gt;
        ///
        ///Nail 123 system trân trọng sự quan tâm của bạn đến với sản phẩm của chúng tôi.
        ///Phản hồi của bạn đang được xem xét và sẽ trả lời trong thời gian sớm nhất.
        ///Hệ thống học trực tuyến Nail 123 system vẫn đang từng bước hoàn thiện mình và rất mong nhận được nhiều ý kiến đóng góp của bạn. &lt;br&gt;
        ///Xin chân thành cảm ơn..
        /// </summary>
        public static string feedbackBody {
            get {
                return ResourceManager.GetString("feedbackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nail 123 system xin chân thành cảm ơn ý kiến đống góp của bạn.
        /// </summary>
        public static string feedbackSubject {
            get {
                return ResourceManager.GetString("feedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0} &lt;br&gt;
        ///Email:{1} &lt;br&gt;
        ///Subject: {2} &lt;br&gt;
        ///Body: {3}.
        /// </summary>
        public static string fromBody {
            get {
                return ResourceManager.GetString("fromBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject: .
        /// </summary>
        public static string fromSubject {
            get {
                return ResourceManager.GetString("fromSubject", resourceCulture);
            }
        }
    }
}
